version: "3"
services:
  simple:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:80
  route:
    build:
      context: .
      dockerfile: Dockerfile-router
    ports:
      - 3000:80