version: "3"
services:
  nginx-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:80
    
  node-app:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - 3003:80
